server:
  port: 8888
  
spring:
  datasource:
     url: jdbc:mysql://192.168.88.130:3306/springboot?useUnicode=true&characterEncoding=utf8
     username: root
     password: 123456
     driver-class-name: com.mysql.jdbc.Driver
  mvc:  
#    view:  
#      prefix: /page/  
#      suffix: .jsp
#配置不要上面图标
     favicon:
      enabled: false        
mybatis:
  mapper-locations: classpath:mapper/*.xml
 

